### ISSUE TITLE
[Feature] move button for 2048

### ISSUE THREAD

**Issue by Rystars** [EVAST9919/lazer-sandbox#18]
![Screenshot_2023-03-05-21-32-08-145_sh ppy osulazer](https://user-images.githubusercontent.com/96302690/222967281-2bc84112-a7d3-4a5f-b8d0-e279c865751a.jpg)

Add up, down, left and right buttons to move in 2048, so it can be played on Android

one more please change the position of the reset button and score tab on the right or left side, if placed above or below then the score tab and reset button are not visible on android

**Comment by EVAST9919** [comment]
Addressed in the latest release
