### ISSUE TITLE
Add support for the original language of tracks in Visualizer 

### ISSUE THREAD

**Issue by Johnny555GH** [EVAST9919/lazer-sandbox#19]
When choosing a track to play in the visualizer, I see the Romanized title of the song on the screen. In the regular osu! settings, I chose to prefer metadata in the original language. In the visualizer, I do not see the original track name. It looks like Visualizer only supports Romanized titles.

**Comment by EVAST9919** [comment]
Added in the [latest release](https://github.com/EVAST9919/lazer-sandbox/releases/tag/2023.422.0)
