### ISSUE TITLE
Particle direction is unexpectedly wrong

### ISSUE THREAD

**Issue by JacksonChen666** [EVAST9919/lazer-sandbox#20]
When you choose a particle direction like "Down", the particles are actually going up. Definately what most people don't expect, and it's a bit awkward.

So the following directions are inverted:
- Left
- Right
- Up
- Down

Those directions correspond to the opposite directions, so the "Left" option makes the particle go right and vice versa.

(Potential reason as to why it's inverted is because the direction is for the camera, not the particle)

**Comment by EVAST9919** [comment]
Fixed in latest release.
