### ISSUE TITLE
An option to disable particle scroll to the song

### ISSUE THREAD

**Issue by NotGumballer91** [EVAST9919/lazer-sandbox#4]
In visualizer, It'll be cool to keep particles in consistent motion than changing to the song

**Comment by EVAST9919** [comment]
Do you mean direction or speed?

**Comment by NotGumballer91** [comment]
Yes. Direction. An option to make keep it one direction and speed

**Comment by EVAST9919** [comment]
Added in [latest update](https://github.com/EVAST9919/lazer-sandbox/releases/tag/2021.1116.0)
